# Generated by Django 5.0.4 on 2024-04-29 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_customuser_delivery_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='delivery_address',
        ),
    ]
